hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("quickshell")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("wal")
    hl.exec_cmd("udiskie --tray")
    hl.exec_cmd("setwall_rand.sh")
end)
