background #131318
foreground #e4e1e9

selection_background #bbc3ff
selection_foreground #232c61

cursor #bbc3ff

color0 #1b1b21
color1 #ffb4ab
color2 #e6bad7
color3 #c4c5dd
color4 #bbc3ff
color5 #c4c5dd
color6 #e6bad7
color7 #e4e1e9

color8 #1f1f25
color9 #ffb4ab
color10 #e6bad7
color11 #c4c5dd
color12 #bbc3ff
color13 #c4c5dd
color14 #e6bad7
color15 #e4e1e9