# Brain Shell Autostarts
exec-once = awww-daemon
exec-once = hypridle
exec-once = qs -p /home/valerius/.local/src/Brain_Shell
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
layerrule = noanim, quickshell
layerrule = noanim, selection
layerrule = ignorealpha 1, selection
source = $HOME/.config/Brain_Shell/Brain_ShellKeybinds.conf
