[config]

[templates.quickshell]
input_path = "~/.config/matugen/templates/colors.json"
output_path = "~/.local/state/quickshell/generated/colors.json"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/matugen.conf"

[templates.steam]
input_path = '~/.config/matugen/templates/steam.css'
output_path = '~/.config/AdwSteamGtk/custom.css'
post_hook = 'adwaita-steam-gtk -i'

[templates.prismlauncher]
input_path = '~/.config/matugen/templates/prismlauncher.json'
output_path = '~/.local/share/PrismLauncher/themes/Matugen/theme.json'

[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian.css'
output_path = '~/notes/.obsidian/snippets/matugen.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.heroic]
input_path = '~/.config/matugen/templates/heroic.css'
output_path = '~/.config/heroic/themes/matugen.css'

[templates.openrgb]
input_path = '~/.config/matugen/templates/openrgb.sh'
output_path = '~/.config/OpenRGB/themes/openrgb.sh'
post_hook = 'source ~/.config/OpenRGB/themes/openrgb.sh && ~/dotfiles/scripts/openrgb_matugen.sh'

[templates.neovim]
input_path = "~/.config/matugen/templates/nvim-colors.json"
output_path = "~/.config/matugen/themes/nvim-colors.json"
post_hook = "pkill -SIGUSR1 nvim"

[templates.zathura]
input_path = '~/.config/matugen/templates/zathura-colors'
output_path = '~/.config/zathura/zathurarc'
