[config]

[templates.quickshell]
input_path = "~/.config/matugen/templates/colors.json"
output_path = "~/.local/state/quickshell/generated/colors.json"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/matugen.conf"

[templates.vscode-raw]
input_path = '~/.config/matugen/templates/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = '~/.config/matugen/templates/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'

[templates.vivaldi]
input_path = "~/.config/matugen/templates/vivaldi.css"
output_path = "~/.config/vivaldi/Default/CustomThemes/matugen.css"

[templates.steam]
input_path = '~/.config/matugen/templates/steam.css'
output_path = '~/.config/AdwSteamGtk/custom.css'
post_hook =  'adwaita-steam-gtk -i'

[templates.prismlauncher]
input_path = '~/.config/matugen/templates/prismlauncher.json'
output_path = '~/.local/share/PrismLauncher/themes/Matugen/theme.json'

[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian.css'
output_path = '~/notes/.obsidian/snippets/matugen.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/colors.rasi'
output_path = '~/.config/rofi/colors.rasi'
